### PR TITLE
fix: duplex only has a getter

### PR DESCRIPTION
**Pull request by wenerme**

### CODE REVIEW

**Comment by usualoma** [comment]
Hi @wenerme 

Thanks for creating the PR! I see what you mean, that is indeed true.

I would like to make some simpler changes to the content, preferably something like the following. Would it be possible to change the content of your PR that way?

```diff
diff --git a/src/request.ts b/src/request.ts
index 94201a7..563fde8 100644
--- a/src/request.ts
+++ b/src/request.ts
@@ -13,7 +13,8 @@ export class Request extends GlobalRequest {
     }
     if (options?.body instanceof ReadableStream) {
       // node 18 fetch needs half duplex mode when request body is stream
-      ;(options as any).duplex = 'half'
+      // if already set, do nothing since a Request object was passed to the options or explicitly set by the user.
+      ;(options as any).duplex ??= 'half'
     }
     super(input, options)
   }
diff --git a/test/request.test.ts b/test/request.test.ts
index 004b6a1..b66cba3 100644
--- a/test/request.test.ts
+++ b/test/request.test.ts
@@ -112,5 +112,21 @@ describe('Request', () => {
       expect(req2).toBeInstanceOf(GlobalRequest)
       expect(req2.text()).resolves.toBe('bar')
     })
+
+    it('should skip to set `duplex: "half"` if init option is a Request object', async () => {
+      const stream = new ReadableStream({
+        start(controller) {
+          controller.enqueue(new TextEncoder().encode('bar'))
+          controller.close()
+        },
+      })
+      const req = new Request('http://localhost', {
+        method: 'POST',
+        body: stream,
+      })
+      const req2 = new Request('http://localhost/subapp', req)
+      expect(req2).toBeInstanceOf(GlobalRequest)
+      expect(req2.text()).resolves.toBe('bar')
+    })
   })
 })
```

**Comment by wenerme** [comment]
Ok with this, reset the patch.

**Comment by alexiglesias93** [comment]
I was just about to open a PR for this, thank you @wenerme! For now I've applied a local patch with these changes and it solved our issues. Looking forward to this PR being merged 🙏

**Comment by usualoma** [comment]
@wenerme Thank you! Looks good to me 👍

**Comment by yusukebe** [comment]
@wenerme @usualoma 

Thanks! Looks good. Merging now.

**Pull request merged**
