### PR TITLE
fix: add TransformStream to global and re-implement stream pipe

### PR DESCRIPTION
**Pull request by tangye1234**
- Rewrite the implementation of `Stream Pipe`, taking inspiration from nodejs' `stream.Readable.fromWeb`, which offers better support for backpressure and highWatermark option.

- Additionally, TransformStream has been added to globals.

### CODE REVIEW

**Comment by tangye1234** [comment]
This patch aims to address a potential memory leak that may occur when pushing large streams into the server response.

The server response features a backpressure mechanism, which causes the upstream to read data more slowly, thereby preventing stress on the response queue.

However without this patch, it can result in a significant increase in memory usage, as the sink may not have the capacity to handle the increased load efficiently.

**Comment by tangye1234** [comment]
https://stackblitz.com/edit/node-mvpjwe?file=index.js
This is a demo to demonstrate that memory leak during huge stream processing.

You event cannot close the server, cause too many objects stuck in the response queue which prevent application to stop.
If you just arange the program a few memory, it will be finally OOM.

**Comment by yusukebe** [comment]
OK, I'll check it later.

**Comment by yusukebe** [comment]
Hi @tangye1234 !

Great work!

I tested your demo on my local machine, and indeed, the current version has memory leaks. However, with this PR, it doesn't consume a large amount of memory. Also, the implementation looks good.

I'll go ahead and merge it.

**Pull request merged**
