### PR TITLE
add listeningListener serve function

### PR DESCRIPTION
**Pull request by ibodev1**

### CODE REVIEW

**Comment by yusukebe** [comment]
HI @ibodev1 !

Thanks for creating the PR.

It looks good, but I'd like to reconsider the API, particularly for functions like `serve`, though it may not be a big change. Therefore, I will leave this PR unmerged for now.

**Comment by ibodev1** [comment]
Hi @yusukebe.

I like your work very much. I like using nodejs very much, I recently started using deno and the hono library is really useful and fast. I have a callback function habit from using node js and express. I had this deficiency in hono and I wanted to open PR. I hope it will help you.

**Review by yusukebe — COMMENTED** [review]
@ibodev1 

Sorry for delay. I like this feature and the API. So, I want to merge it.
I've leaved one comment. Check it!

**Comment by ibodev1** [comment]
I made the updates you asked for and committed it. I hope it worked for you. I made an update in the readme file about how the listener is used.

**Comment by ibodev1** [comment]
I edited the readme file under the heading "Usage" instead of opening a separate heading. it is more readable this way.

**Comment by yusukebe** [comment]
Hi @ibodev1 !

Perfect! I'll merge it now. Thanks for your contribution!

**Comment by ibodev1** [comment]
you are welcome. see you in other projects :)

**Pull request merged**
