### PR TITLE
refactor(test): replace features to be removed in v4

### PR DESCRIPTION
**Pull request by ryuapp**

### CODE REVIEW

**Comment by ryuapp** [comment]
It need at least Hono 3.12.x to pass the test because `hono/streming`  is added in the version.

**Comment by yusukebe** [comment]
Hi @ryuapp 

It has already been upgraded to v3.12.8 in the main branch. So you can sync.

**Comment by ryuapp** [comment]
@yusukebe 
Oops, thanks. I have synced this branch.

**Comment by yusukebe** [comment]
@ryuapp 

Cool! Merging now. Thanks.

**Pull request merged**
