### PR TITLE
feat: implement ConnInfo helper

### PR DESCRIPTION
**Pull request by nakasyou**
I implemented [ConnInfo helper](https://hono.dev/docs/helpers/conninfo) for Node.js.

Example:
```ts
import { Hono } from 'hono'
import { serve } from '@hono/node-server'
import { getConnInfo } from '@hono/node-server/conninfo'

const app = new Hono()
app.get('/ip-address', c => c.text(`Your IP Address: ${getConnInfo(c).remote.address}`))

serve(app)
```

The helper uses env to get Node.js HTTP Bindings.
If you'd like to use env, you can write code like:
```ts
serve({
  fetch (req, server) {
    return app.get(req, { server })
  }
})
```

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @nakasyou 

I'll review it but, should we upgrade `hono` package?

**Comment by nakasyou** [comment]
@yusukebe probably yes.

**Comment by usualoma** [comment]
Good 👍

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Hi @nakasyou 

I've updated the branch to pass the CI. Looks good. Merging now. Thanks!

**Pull request merged**
